using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PCL.Core.SourceGenerators;

[Generator]
public class JsonContextGenerator: IIncrementalGenerator
{
    
    private static readonly DiagnosticDescriptor GenericTypeNotSupported =
        new(
            id: "JSON001",
            title: "Generic type is not supported",
            messageFormat: "Type '{0}' is generic and cannot be used with GenerateJsonContext",
            category: "JsonGenerator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

    private const string ExceptAttributeNamespace = "PCL.Core.Utils.Json";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider<JsonObjectAnalyzeResult>(
            predicate: (node, _) => node switch
            {
                ClassDeclarationSyntax classDef => classDef.AttributeLists.Count != 0,
                StructDeclarationSyntax structDef => structDef.AttributeLists.Count != 0,
                RecordDeclarationSyntax recordDef => recordDef.AttributeLists.Count != 0,
                _ => false
            },
            transform: (compilerContext, _) =>
            {
                var result = new JsonObjectAnalyzeResult();
                var node = compilerContext.Node;



                var semanticModel = compilerContext.SemanticModel;
                INamedTypeSymbol? symbol = null;
                if (node is ClassDeclarationSyntax classDef)
                {
                    symbol = semanticModel.GetDeclaredSymbol(classDef);
                }
                else if (node is StructDeclarationSyntax structDef)
                {
                    symbol = semanticModel.GetDeclaredSymbol(structDef);
                }
                else if (node is RecordDeclarationSyntax recordDef)
                {
                    symbol = semanticModel.GetDeclaredSymbol(recordDef);
                }
                else
                {
                    return null;
                }

                if (symbol is null) return null;

                var attr = symbol.GetAttributes()
                    .FirstOrDefault(x => x.AttributeClass?.Name == "GenerateJsonContextAttribute"
                                         && x.AttributeClass.ContainingNamespace.ToDisplayString() ==
                                         ExceptAttributeNamespace);
                if (attr is null) return null;
                if (symbol.TypeParameters.Length != 0)
                    result.Report.Add(Diagnostic.Create(GenericTypeNotSupported, symbol.Locations.FirstOrDefault(),
                        symbol.ToDisplayString()));
                
                var members = symbol.GetMembers().OfType<IPropertySymbol>();
                foreach (var m in members)
                {
                    var name = (string?)m.GetAttributes()
                        .FirstOrDefault(a => 
                            a.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute")?
                        .ConstructorArguments.First().Value;
                    result.ContextCollection.Add(new JsonContextInformation
                    {
                        Key = string.IsNullOrEmpty(name) ? m.Name : name,
                        TokenType = m.Type.SpecialType switch
                        {
                            SpecialType.System_String => JsonPropertyType.String | _ShouldBeRequireOrNullable(m),
                            SpecialType.System_Int32 or SpecialType.System_Int16 => JsonPropertyType.Int32 | _ShouldBeRequireOrNullable(m),
                            SpecialType.System_Int64 => JsonPropertyType.Int64 | _ShouldBeRequireOrNullable(m),
                            SpecialType.System_Double => JsonPropertyType.Double | _ShouldBeRequireOrNullable(m),
                            SpecialType.System_Boolean => JsonPropertyType.Boolean | _ShouldBeRequireOrNullable(m),
                            _ => JsonPropertyType.None
                        }
                    });
                }

                return result;
            });
        var infos = provider.Collect();
        context.RegisterSourceOutput(infos, (productionContext, array) =>
        {
            var sb = new StringBuilder();
            sb.AppendLine("// =================== WARNING =======================");
            sb.AppendLine("//");
            sb.AppendLine("// This file was auto-generated by JsonContext Generator.");
            sb.AppendLine("//");
            sb.AppendLine("// DO NOT edit or delete this file. All changes will be discard.");
            sb.AppendLine("//");
            sb.AppendLine("// ====================================================");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Collections.Concurrent;");
            sb.AppendLine("using System.Text.Json.Serialization;");
            sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
            sb.AppendLine("");
            sb.AppendLine($"namespace {ExceptAttributeNamespace};");
            sb.AppendLine("");
            sb.AppendLine("internal partial class JsonResolver:IJsonTypeInfoResolver");
            sb.AppendLine("{");
            sb.AppendLine("}");
            productionContext.AddSource("JsonResolver.g.cs", sb.ToString());
        });
        
    }

    private JsonPropertyType _ShouldBeRequireOrNullable(IPropertySymbol m)
    {
        return (m.NullableAnnotation == NullableAnnotation.Annotated ? JsonPropertyType.Null : JsonPropertyType.None)
               | (m.IsRequired ? JsonPropertyType.Required : JsonPropertyType.None);
    }
    public class JsonContextInformation
    {
        public string? Key { get; set; }
        public JsonPropertyType? TokenType { get; set; }
        
    }
    
    [Flags]
    public enum JsonPropertyType
    {
        None = 0,
        String   = 1 << 0,
        Int32    = 1 << 1, 
        Int64    = 1 << 2,
        Double   = 1 << 3,
        Boolean  = 1 << 4, 
        Null     = 1 << 5, 
        Required = 1 << 6 
    }

    public class JsonObjectAnalyzeResult
    {
        public List<JsonContextInformation> ContextCollection { get; set; } = [];
        public List<Diagnostic> Report { get; set; } = [];
    }
}