/* This file is generated by DeepSeek */

using System;
using System.Windows;
using System.Windows.Controls;

namespace PCL.Core.UI.Controls;

public class WaterfallPanel : Panel
{
    /// <summary>
    /// 列数（可依赖属性，支持动态变化）
    /// </summary>
    public int ColumnCount
    {
        get { return (int)GetValue(ColumnCountProperty); }
        set { SetValue(ColumnCountProperty, value); }
    }

    public static readonly DependencyProperty ColumnCountProperty =
        DependencyProperty.Register(nameof(ColumnCount), typeof(int), typeof(WaterfallPanel),
            new FrameworkPropertyMetadata(2, FrameworkPropertyMetadataOptions.AffectsMeasure));

    /// <summary>
    /// 列间距
    /// </summary>
    public double ColumnSpacing
    {
        get { return (double)GetValue(ColumnSpacingProperty); }
        set { SetValue(ColumnSpacingProperty, value); }
    }

    public static readonly DependencyProperty ColumnSpacingProperty =
        DependencyProperty.Register(nameof(ColumnSpacing), typeof(double), typeof(WaterfallPanel),
            new FrameworkPropertyMetadata(5.0, FrameworkPropertyMetadataOptions.AffectsMeasure));

    protected override Size MeasureOverride(Size availableSize)
    {
        // 计算每列的实际宽度（考虑列间距）
        double colWidth = (availableSize.Width - (ColumnCount - 1) * ColumnSpacing) / ColumnCount;
        colWidth = Math.Max(0, colWidth);

        // 存储每列当前的高度（用于后续布局）
        double[] colHeights = new double[ColumnCount];

        // 对每个子元素进行测量
        foreach (UIElement child in InternalChildren)
        {
            // 约束子元素宽度为列宽，高度不限
            child.Measure(new Size(colWidth, double.PositiveInfinity));
            Size desiredSize = child.DesiredSize;

            // 找到当前高度最小的列
            int minColIndex = _GetMinHeightColumnIndex(colHeights);
            colHeights[minColIndex] += desiredSize.Height;
            // 如果是非第一项，加上行间距（这里简单处理，可添加 RowSpacing 属性）
            // 此处省略行间距，您可以根据需要添加
        }

        // 返回面板所需的总高度 = 最高列的高度
        double totalHeight = 0;
        foreach (double h in colHeights)
        {
            totalHeight = Math.Max(totalHeight, h);
        }
        return new Size(availableSize.Width, totalHeight);
    }

    protected override Size ArrangeOverride(Size finalSize)
    {
        double colWidth = (finalSize.Width - (ColumnCount - 1) * ColumnSpacing) / ColumnCount;
        colWidth = Math.Max(0, colWidth);

        double[] colHeights = new double[ColumnCount]; // 记录每列当前已占用的高度

        foreach (UIElement child in InternalChildren)
        {
            // 找到当前高度最小的列
            int colIndex = _GetMinHeightColumnIndex(colHeights);
            double x = colIndex * (colWidth + ColumnSpacing);
            double y = colHeights[colIndex];

            // 安排子元素位置
            child.Arrange(new Rect(new Point(x, y), new Size(colWidth, child.DesiredSize.Height)));

            // 更新该列高度
            colHeights[colIndex] += child.DesiredSize.Height;
            // 如果需要行间距，可以在此处添加：colHeights[colIndex] += RowSpacing;
        }

        return finalSize;
    }

    private int _GetMinHeightColumnIndex(double[] colHeights)
    {
        int minIndex = 0;
        double minHeight = colHeights[0];
        for (int i = 1; i < colHeights.Length; i++)
        {
            if (colHeights[i] < minHeight)
            {
                minHeight = colHeights[i];
                minIndex = i;
            }
        }
        return minIndex;
    }
}