// Copyright (c) MUXUE1230. All rights reserved.
// Modifications Copyright (c) 2026 PCL N contributors.
// Licensed under the Apache License, Version 2.0.

using System.Runtime.CompilerServices;
using PCL.Core.App;
using PCL.Core.App.Cli;
using PCL.Core.Link.McPing;
using PCL.Core.Link.McPing.Model;
using PCL.Core.Link.Scaffolding;
using PCL.Core.IO.Download;
using PCL.Core.Minecraft.Saves;
using PCL.Core.Minecraft.Saves.Editing;
using PCL.Core.Minecraft.Saves.Exceptions;
using PCL.Core.Minecraft.Saves.Parsing;
using PCL.Core.Minecraft.IdentityModel;
using PCL.Core.Minecraft.IdentityModel.Extensions.JsonWebToken;
using PCL.Core.Minecraft.IdentityModel.Extensions.OpenId;
using PCL.Core.Minecraft.IdentityModel.Extensions.Pkce;
using PCL.Core.Minecraft.IdentityModel.Extensions.YggdrasilConnect;
using PCL.Core.Minecraft.IdentityModel.OAuth;
using PCL.Core.Utils;
using PCL.Core.Utils.Codecs;
using PCL.Core.Utils.Diff;
using PCL.Core.Utils.Encryption;
using PCL.Core.Utils.Threading;

[assembly: TypeForwardedTo(typeof(ArgumentValueKind))]
[assembly: TypeForwardedTo(typeof(ColorMode))]
[assembly: TypeForwardedTo(typeof(ColorTheme))]
[assembly: TypeForwardedTo(typeof(UpdateChannel))]
[assembly: TypeForwardedTo(typeof(GameWindowSizeMode))]
[assembly: TypeForwardedTo(typeof(GameProcessPriority))]
[assembly: TypeForwardedTo(typeof(LauncherVisibility))]
[assembly: TypeForwardedTo(typeof(JvmPreferredIpStack))]
[assembly: TypeForwardedTo(typeof(LauncherAutoUpdateBehavior))]
[assembly: TypeForwardedTo(typeof(LauncherTitleType))]
[assembly: TypeForwardedTo(typeof(BoolArgument))]
[assembly: TypeForwardedTo(typeof(CommandArgument))]
[assembly: TypeForwardedTo(typeof(CommandArgument<>))]
[assembly: TypeForwardedTo(typeof(CommandLine))]
[assembly: TypeForwardedTo(typeof(CommandLineJsonConverter))]
[assembly: TypeForwardedTo(typeof(DecimalArgument))]
[assembly: TypeForwardedTo(typeof(SubcommandDefinition))]
[assembly: TypeForwardedTo(typeof(TextArgument))]
[assembly: TypeForwardedTo(typeof(SemVer))]
[assembly: TypeForwardedTo(typeof(VersionRange))]
[assembly: TypeForwardedTo(typeof(ArgumentsBuilder))]
[assembly: TypeForwardedTo(typeof(AtomicVariable<>))]
[assembly: TypeForwardedTo(typeof(ConcurrentSet<>))]
[assembly: TypeForwardedTo(typeof(ParameterizedProperty<,>))]
[assembly: TypeForwardedTo(typeof(Result<,>))]
[assembly: TypeForwardedTo(typeof(SearchEntry<>))]
[assembly: TypeForwardedTo(typeof(SimilaritySearch))]
[assembly: TypeForwardedTo(typeof(StringStream))]
[assembly: TypeForwardedTo(typeof(VarIntHelper))]
[assembly: TypeForwardedTo(typeof(EncodingDetector))]
[assembly: TypeForwardedTo(typeof(Encodings))]
[assembly: TypeForwardedTo(typeof(EncodingUtils))]
[assembly: TypeForwardedTo(typeof(BsDiff))]
[assembly: TypeForwardedTo(typeof(IBinaryDiff))]
[assembly: TypeForwardedTo(typeof(ItemDiff))]
[assembly: TypeForwardedTo(typeof(ItemDiffResult<>))]
[assembly: TypeForwardedTo(typeof(AesCbcProvider))]
[assembly: TypeForwardedTo(typeof(AesGcmProvider))]
[assembly: TypeForwardedTo(typeof(ChaCha20Poly1305Provider))]
[assembly: TypeForwardedTo(typeof(ChaCha20SoftwareProvider))]
[assembly: TypeForwardedTo(typeof(IEncryptionProvider))]
[assembly: TypeForwardedTo(typeof(AsyncCountResetEvent))]
[assembly: TypeForwardedTo(typeof(AsyncDebounce))]
[assembly: TypeForwardedTo(typeof(AsyncManualResetEvent))]
[assembly: TypeForwardedTo(typeof(DualThreadPool))]
[assembly: TypeForwardedTo(typeof(LimitedConcurrencyLevelTaskScheduler))]
[assembly: TypeForwardedTo(typeof(LimitedTaskPool))]
[assembly: TypeForwardedTo(typeof(DataVersionBoundaries))]
[assembly: TypeForwardedTo(typeof(Difficulty))]
[assembly: TypeForwardedTo(typeof(GameMode))]
[assembly: TypeForwardedTo(typeof(SaveFormatVersion))]
[assembly: TypeForwardedTo(typeof(SaveInfo))]
[assembly: TypeForwardedTo(typeof(SaveManager))]
[assembly: TypeForwardedTo(typeof(Editable<>))]
[assembly: TypeForwardedTo(typeof(ISaveEditor))]
[assembly: TypeForwardedTo(typeof(SaveChanges))]
[assembly: TypeForwardedTo(typeof(SaveCorruptedException))]
[assembly: TypeForwardedTo(typeof(SaveNotFoundException))]
[assembly: TypeForwardedTo(typeof(ISaveParser))]
[assembly: TypeForwardedTo(typeof(SaveParserFactory))]
[assembly: TypeForwardedTo(typeof(IMcPingService))]
[assembly: TypeForwardedTo(typeof(LegacyMcPingService))]
[assembly: TypeForwardedTo(typeof(McPingService))]
[assembly: TypeForwardedTo(typeof(McPingServiceFactory))]
[assembly: TypeForwardedTo(typeof(McPingModInfoModResult))]
[assembly: TypeForwardedTo(typeof(McPingModInfoResult))]
[assembly: TypeForwardedTo(typeof(McPingPlayerResult))]
[assembly: TypeForwardedTo(typeof(McPingPlayerSampleResult))]
[assembly: TypeForwardedTo(typeof(McPingResult))]
[assembly: TypeForwardedTo(typeof(McPingVersionResult))]
[assembly: TypeForwardedTo(typeof(LobbyCodeGenerator))]
[assembly: TypeForwardedTo(typeof(IDlResourceMapping<>))]
[assembly: TypeForwardedTo(typeof(NDlFactory))]
[assembly: TypeForwardedTo(typeof(NDlFactory<,>))]
[assembly: TypeForwardedTo(typeof(NDlSourceReport))]
[assembly: TypeForwardedTo(typeof(DownloadStage))]
[assembly: TypeForwardedTo(typeof(DownloadProgress))]
[assembly: TypeForwardedTo(typeof(DownloadAttemptError))]
[assembly: TypeForwardedTo(typeof(DownloadRequest))]
[assembly: TypeForwardedTo(typeof(DownloadTransferResult))]
[assembly: TypeForwardedTo(typeof(DownloadService))]
[assembly: TypeForwardedTo(typeof(IdentityModelException))]
[assembly: TypeForwardedTo(typeof(IdentityModelConfigurationException))]
[assembly: TypeForwardedTo(typeof(IdentityModelAuthenticationException))]
[assembly: TypeForwardedTo(typeof(AuthorizeResult))]
[assembly: TypeForwardedTo(typeof(DeviceCodeData))]
[assembly: TypeForwardedTo(typeof(EndpointMeta))]
[assembly: TypeForwardedTo(typeof(IOAuthClient))]
[assembly: TypeForwardedTo(typeof(OAuthClientOptions))]
[assembly: TypeForwardedTo(typeof(SimpleOAuthClient))]
[assembly: TypeForwardedTo(typeof(PkceChallengeOptions))]
[assembly: TypeForwardedTo(typeof(PkceClient))]
[assembly: TypeForwardedTo(typeof(JsonWebKeyData))]
[assembly: TypeForwardedTo(typeof(JsonWebKeys))]
[assembly: TypeForwardedTo(typeof(JsonWebToken))]
[assembly: TypeForwardedTo(typeof(OpenIdMetadata))]
[assembly: TypeForwardedTo(typeof(OpenIdOptions))]
[assembly: TypeForwardedTo(typeof(OpenIdClient))]
[assembly: TypeForwardedTo(typeof(YggdrasilConnectMetaData))]
[assembly: TypeForwardedTo(typeof(YggdrasilOptions))]
[assembly: TypeForwardedTo(typeof(YggdrasilClient))]
