using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PCL.Desktop.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class DesktopNavigationRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "PCL.Desktop.Hosting.DesktopNavigationPageAttribute";
    private const string RegistryMetadataName = "PCL.Desktop.Hosting.DesktopNavigationRegistry";

    private static readonly DiagnosticDescriptor InvalidTargetDescriptor = new(
        "PCLDNAV001",
        "Invalid desktop navigation declaration",
        "Desktop navigation page method '{0}' must be declared on PCL.Desktop.Hosting.DesktopNavigationRegistry",
        "PCL.Desktop.Navigation",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Desktop navigation declarations are statically generated for Native AOT and must stay in the built-in registry type.");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pages = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetNavigationPage(ctx, cancellationToken))
            .Where(static page => page is not null)
            .Collect();

        context.RegisterSourceOutput(pages, static (spc, collected) => GenerateRegistry(spc, collected));
    }

    private static NavigationPageModel? GetNavigationPage(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not IMethodSymbol method)
            return null;

        AttributeData? attribute = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.ToDisplayString() == AttributeMetadataName);
        if (attribute is null || attribute.ConstructorArguments.Length < 5)
            return null;

        string? moduleId = attribute.ConstructorArguments[0].Value as string;
        string? route = attribute.ConstructorArguments[1].Value as string;
        string? title = attribute.ConstructorArguments[2].Value as string;
        string? icon = attribute.ConstructorArguments[3].Value as string;
        int order = attribute.ConstructorArguments[4].Value is int rawOrder ? rawOrder : 0;

        return new NavigationPageModel(
            method,
            moduleId ?? string.Empty,
            route ?? string.Empty,
            title ?? string.Empty,
            icon ?? string.Empty,
            order);
    }

    private static void GenerateRegistry(
        SourceProductionContext context,
        ImmutableArray<NavigationPageModel?> nullablePages)
    {
        List<NavigationPageModel> pages = nullablePages
            .Where(static page => page is not null)
            .Select(static page => page!)
            .OrderBy(static page => page.Order)
            .ThenBy(static page => page.Route, StringComparer.Ordinal)
            .ToList();

        foreach (NavigationPageModel page in pages)
        {
            if (page.Method.ContainingType.ToDisplayString() != RegistryMetadataName)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidTargetDescriptor,
                    page.Method.Locations.FirstOrDefault(),
                    page.Method.Name));
                return;
            }
        }

        StringBuilder sb = new(4096);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由 Source Generator 自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PCL.Desktop.Hosting;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class DesktopNavigationRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.DesktopNavigationRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial void RegisterGeneratedHostModules(global::PCL.Application.Hosting.PclHostBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(builder);");
        foreach (NavigationPageModel page in pages)
        {
            sb.AppendLine("        builder.AddModule(");
            sb.Append("            new global::PCL.Application.Hosting.HostModuleId(").Append(ToLiteral(page.ModuleId)).AppendLine("),");
            sb.AppendLine("            static hostBuilder => global::PCL.Desktop.Hosting.DesktopNavigationModule.AddPage(");
            sb.AppendLine("                hostBuilder.Navigation,");
            sb.Append("                new global::PCL.UI.Abstractions.Navigation.NavigationRouteId(").Append(ToLiteral(page.Route)).AppendLine("),");
            sb.Append("                ").Append(ToLiteral(page.Title)).AppendLine(",");
            sb.Append("                ").Append(ToLiteral(page.Icon)).AppendLine(",");
            sb.Append("                ").Append(page.Order).AppendLine(",");
            sb.Append("                static context => ").Append(page.Method.Name).AppendLine("(context)));");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "DesktopNavigationRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ToLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private sealed class NavigationPageModel
    {
        public NavigationPageModel(
            IMethodSymbol method,
            string moduleId,
            string route,
            string title,
            string icon,
            int order)
        {
            Method = method;
            ModuleId = moduleId;
            Route = route;
            Title = title;
            Icon = icon;
            Order = order;
        }

        public IMethodSymbol Method { get; }

        public string ModuleId { get; }

        public string Route { get; }

        public string Title { get; }

        public string Icon { get; }

        public int Order { get; }
    }
}
