// Copyright (c) MUXUE1230. All rights reserved.
// Modifications Copyright (c) 2026 PCL N contributors.
// Licensed under the Apache License, Version 2.0.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PCL.Desktop.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class DownloadPageRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "PCL.Desktop.Features.Downloads.Views.DownloadPageAttribute";
    private const string RegistryMetadataName = "PCL.Desktop.Features.Downloads.Views.DownloadPageRegistry";

    private static readonly DiagnosticDescriptor InvalidTargetDescriptor = new(
        "PCLDDWN001",
        "Invalid download page declaration",
        "Download page method '{0}' must be declared on PCL.Desktop.Features.Downloads.Views.DownloadPageRegistry",
        "PCL.Desktop.Downloads",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Download page declarations are statically generated and must stay in the built-in registry type.");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<DownloadPageModel?>> pages = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetDownloadPage(ctx, cancellationToken))
            .Where(static page => page is not null)
            .Collect();

        context.RegisterSourceOutput(pages, static (spc, collected) => GenerateRegistry(spc, collected));
    }

    private static DownloadPageModel? GetDownloadPage(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not IMethodSymbol method)
            return null;

        AttributeData? attribute = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.ToDisplayString() == AttributeMetadataName);
        if (attribute is null || attribute.ConstructorArguments.Length < 2)
            return null;

        TypedConstant pageArg = attribute.ConstructorArguments[0];
        string pageName = GetEnumExpression(pageArg);
        string? title = attribute.ConstructorArguments[1].Value as string;
        int order = pageArg.Value is int rawValue ? rawValue : 0;

        return new DownloadPageModel(
            method,
            pageName,
            title ?? string.Empty,
            order);
    }

    private static void GenerateRegistry(
        SourceProductionContext context,
        ImmutableArray<DownloadPageModel?> nullablePages)
    {
        List<DownloadPageModel> pages = nullablePages
            .Where(static page => page is not null)
            .Select(static page => page!)
            .OrderBy(static page => page.Order)
            .ThenBy(static page => page.PageExpression, StringComparer.Ordinal)
            .ToList();

        foreach (DownloadPageModel page in pages)
        {
            if (page.Method.ContainingType.ToDisplayString() != RegistryMetadataName)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidTargetDescriptor,
                    page.Method.Locations.FirstOrDefault(),
                    page.Method.Name));
                return;
            }
        }

        StringBuilder sb = new(4096);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由 Source Generator 自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PCL.Desktop.Features.Downloads.Views;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class DownloadPageRegistry");
        sb.AppendLine("{");
        AppendIsDefined(sb, pages);
        sb.AppendLine();
        AppendCreatePage(sb, pages);
        sb.AppendLine();
        AppendGetTitle(sb, pages);
        sb.AppendLine("}");

        context.AddSource(
            "DownloadPageRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendIsDefined(StringBuilder sb, IReadOnlyList<DownloadPageModel> pages)
    {
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.DownloadPageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial bool IsDefined(global::PCL.Desktop.Features.Downloads.Views.DownloadPageSubType page) =>");
        if (pages.Count == 0)
        {
            sb.AppendLine("        false;");
            return;
        }

        sb.Append("        page is ");
        sb.Append(string.Join(" or ", pages.Select(static page => page.PageExpression)));
        sb.AppendLine(";");
    }

    private static void AppendCreatePage(StringBuilder sb, IReadOnlyList<DownloadPageModel> pages)
    {
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.DownloadPageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial global::PCL.Desktop.Controls.Legacy.MyPageRight CreatePage(");
        sb.AppendLine("        global::PCL.Desktop.Features.Downloads.Views.DownloadPageSubType page,");
        sb.AppendLine("        global::PCL.Desktop.Features.Downloads.Views.DownloadPageFactoryContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(context);");
        sb.AppendLine("        return page switch");
        sb.AppendLine("        {");
        foreach (DownloadPageModel page in pages)
            sb.Append("            ").Append(page.PageExpression).Append(" => ").Append(page.Method.Name).AppendLine("(context),");
        sb.AppendLine("            _ => throw new global::System.ArgumentOutOfRangeException(nameof(page), page, \"未知的下载页面。\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void AppendGetTitle(StringBuilder sb, IReadOnlyList<DownloadPageModel> pages)
    {
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.DownloadPageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial string GetTitle(global::PCL.Desktop.Features.Downloads.Views.DownloadPageSubType page) =>");
        sb.AppendLine("        page switch");
        sb.AppendLine("        {");
        foreach (DownloadPageModel page in pages)
            sb.Append("            ").Append(page.PageExpression).Append(" => ").Append(ToLiteral(page.Title)).AppendLine(",");
        sb.AppendLine("            _ => \"下载\"");
        sb.AppendLine("        };");
    }

    private static string ToLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private static string GetEnumExpression(TypedConstant value)
    {
        if (value.Type is not INamedTypeSymbol enumType || value.Value is null)
            return string.Empty;

        foreach (ISymbol member in enumType.GetMembers())
        {
            if (member is IFieldSymbol { HasConstantValue: true } field &&
                Equals(field.ConstantValue, value.Value))
            {
                return enumType.ToDisplayString() + "." + field.Name;
            }
        }

        return enumType.ToDisplayString() + "." + value.Value;
    }

    private sealed class DownloadPageModel
    {
        public DownloadPageModel(
            IMethodSymbol method,
            string pageExpression,
            string title,
            int order)
        {
            Method = method;
            PageExpression = pageExpression;
            Title = title;
            Order = order;
        }

        public IMethodSymbol Method { get; }

        public string PageExpression { get; }

        public string Title { get; }

        public int Order { get; }
    }
}
