using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PCL.Desktop.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class InstancePageRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "PCL.Desktop.Features.Instances.Views.InstancePageAttribute";
    private const string RegistryMetadataName = "PCL.Desktop.Features.Instances.Views.InstancePageRegistry";

    private static readonly DiagnosticDescriptor InvalidTargetDescriptor = new(
        "PCLDINS001",
        "Invalid instance page declaration",
        "Instance page method '{0}' must be declared on PCL.Desktop.Features.Instances.Views.InstancePageRegistry",
        "PCL.Desktop.Instances",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Instance page declarations are statically generated and must stay in the built-in registry type.");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pages = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetInstancePage(ctx, cancellationToken))
            .Where(static page => page is not null)
            .Collect();

        context.RegisterSourceOutput(pages, static (spc, collected) => GenerateRegistry(spc, collected));
    }

    private static InstancePageModel? GetInstancePage(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not IMethodSymbol method)
            return null;

        AttributeData? attribute = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.ToDisplayString() == AttributeMetadataName);
        if (attribute is null || attribute.ConstructorArguments.Length < 5)
            return null;

        TypedConstant pageArg = attribute.ConstructorArguments[0];
        string pageName = GetEnumExpression(pageArg);
        int order = pageArg.Value is int rawValue ? rawValue : 0;
        string title = attribute.ConstructorArguments[1].Value as string ?? string.Empty;
        string description = attribute.ConstructorArguments[2].Value as string ?? string.Empty;
        string folderRelativePath = attribute.ConstructorArguments[3].Value as string ?? string.Empty;
        bool usesGenericFolderPage = attribute.ConstructorArguments[4].Value is bool rawGeneric && rawGeneric;
        string resourceKind = attribute.ConstructorArguments.Length >= 6
            ? GetEnumExpression(attribute.ConstructorArguments[5])
            : "PCL.Desktop.Features.Instances.Views.InstanceResourceKind.None";

        return new InstancePageModel(
            method,
            pageName,
            order,
            title,
            description,
            folderRelativePath,
            usesGenericFolderPage,
            resourceKind);
    }

    private static void GenerateRegistry(
        SourceProductionContext context,
        ImmutableArray<InstancePageModel?> nullablePages)
    {
        List<InstancePageModel> pages = nullablePages
            .Where(static page => page is not null)
            .Select(static page => page!)
            .OrderBy(static page => page.Order)
            .ThenBy(static page => page.PageExpression, StringComparer.Ordinal)
            .ToList();

        foreach (InstancePageModel page in pages)
        {
            if (page.Method.ContainingType.ToDisplayString() != RegistryMetadataName)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidTargetDescriptor,
                    page.Method.Locations.FirstOrDefault(),
                    page.Method.Name));
                return;
            }
        }

        StringBuilder sb = new(8192);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由 Source Generator 自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PCL.Desktop.Features.Instances.Views;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class InstancePageRegistry");
        sb.AppendLine("{");
        AppendBooleanMatcher(sb, "IsDefined", pages, static _ => true);
        sb.AppendLine();
        AppendBooleanMatcher(sb, "UsesGenericFolderPage", pages, static page => page.UsesGenericFolderPage);
        sb.AppendLine();
        AppendStringSwitch(sb, "GetTitle", pages, static page => page.Title, "资源");
        sb.AppendLine();
        AppendStringSwitch(sb, "GetDescription", pages, static page => page.Description, "管理当前 Minecraft 根目录下的资源文件。");
        sb.AppendLine();
        AppendStringSwitch(sb, "GetFolderRelativePath", pages, static page => page.FolderRelativePath, string.Empty);
        sb.AppendLine();
        AppendResourceKindSwitch(sb, pages);
        sb.AppendLine("}");

        context.AddSource(
            "InstancePageRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendResourceKindSwitch(
        StringBuilder sb,
        IReadOnlyList<InstancePageModel> pages)
    {
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.InstancePageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial global::PCL.Desktop.Features.Instances.Views.InstanceResourceKind GetResourceKind(global::PCL.Desktop.Features.Instances.Views.InstancePageSubType page) =>");
        sb.AppendLine("        page switch");
        sb.AppendLine("        {");
        foreach (InstancePageModel page in pages)
            sb.Append("            ").Append(page.PageExpression).Append(" => ").Append(page.ResourceKindExpression).AppendLine(",");
        sb.AppendLine("            _ => global::PCL.Desktop.Features.Instances.Views.InstanceResourceKind.None");
        sb.AppendLine("        };");
    }

    private static void AppendBooleanMatcher(
        StringBuilder sb,
        string methodName,
        IReadOnlyList<InstancePageModel> pages,
        Func<InstancePageModel, bool> predicate)
    {
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.InstancePageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.Append("    public static partial bool ").Append(methodName).AppendLine("(global::PCL.Desktop.Features.Instances.Views.InstancePageSubType page) =>");

        List<InstancePageModel> matches = pages.Where(predicate).ToList();
        if (matches.Count == 0)
        {
            sb.AppendLine("        false;");
            return;
        }

        sb.Append("        page is ");
        sb.Append(string.Join(" or ", matches.Select(static page => page.PageExpression)));
        sb.AppendLine(";");
    }

    private static void AppendStringSwitch(
        StringBuilder sb,
        string methodName,
        IReadOnlyList<InstancePageModel> pages,
        Func<InstancePageModel, string> selector,
        string defaultValue)
    {
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.InstancePageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.Append("    public static partial string ").Append(methodName).AppendLine("(global::PCL.Desktop.Features.Instances.Views.InstancePageSubType page) =>");
        sb.AppendLine("        page switch");
        sb.AppendLine("        {");
        foreach (InstancePageModel page in pages)
            sb.Append("            ").Append(page.PageExpression).Append(" => ").Append(ToLiteral(selector(page))).AppendLine(",");
        sb.Append("            _ => ").Append(ToLiteral(defaultValue)).AppendLine();
        sb.AppendLine("        };");
    }

    private static string ToLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private static string GetEnumExpression(TypedConstant value)
    {
        if (value.Type is not INamedTypeSymbol enumType || value.Value is null)
            return string.Empty;

        foreach (ISymbol member in enumType.GetMembers())
        {
            if (member is IFieldSymbol { HasConstantValue: true } field &&
                Equals(field.ConstantValue, value.Value))
            {
                return enumType.ToDisplayString() + "." + field.Name;
            }
        }

        return enumType.ToDisplayString() + "." + value.Value;
    }

    private sealed class InstancePageModel
    {
        public InstancePageModel(
            IMethodSymbol method,
            string pageExpression,
            int order,
            string title,
            string description,
            string folderRelativePath,
            bool usesGenericFolderPage,
            string resourceKindExpression)
        {
            Method = method;
            PageExpression = pageExpression;
            Order = order;
            Title = title;
            Description = description;
            FolderRelativePath = folderRelativePath;
            UsesGenericFolderPage = usesGenericFolderPage;
            ResourceKindExpression = resourceKindExpression;
        }

        public IMethodSymbol Method { get; }

        public string PageExpression { get; }

        public int Order { get; }

        public string Title { get; }

        public string Description { get; }

        public string FolderRelativePath { get; }

        public bool UsesGenericFolderPage { get; }

        public string ResourceKindExpression { get; }
    }
}
