using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace PCL.Desktop.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class SetupPageRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "PCL.Desktop.Features.Settings.Views.SetupPageAttribute";
    private const string RegistryMetadataName = "PCL.Desktop.Features.Settings.Views.SetupPageRegistry";

    private static readonly DiagnosticDescriptor InvalidTargetDescriptor = new(
        "PCLDSET001",
        "Invalid setup page declaration",
        "Setup page method '{0}' must be declared on PCL.Desktop.Features.Settings.Views.SetupPageRegistry",
        "PCL.Desktop.Settings",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Setup page declarations are statically generated and must stay in the built-in registry type.");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pages = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetSetupPage(ctx, cancellationToken))
            .Where(static page => page is not null)
            .Collect();

        context.RegisterSourceOutput(pages, static (spc, collected) => GenerateRegistry(spc, collected));
    }

    private static SetupPageModel? GetSetupPage(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not IMethodSymbol method)
            return null;

        AttributeData? attribute = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.ToDisplayString() == AttributeMetadataName);
        if (attribute is null || attribute.ConstructorArguments.Length < 2)
            return null;

        TypedConstant pageArg = attribute.ConstructorArguments[0];
        string pageName = GetEnumExpression(pageArg);
        string? title = attribute.ConstructorArguments[1].Value as string;
        int order = pageArg.Value is int rawValue ? rawValue : 0;

        return new SetupPageModel(
            method,
            pageName,
            title ?? string.Empty,
            order);
    }

    private static void GenerateRegistry(
        SourceProductionContext context,
        ImmutableArray<SetupPageModel?> nullablePages)
    {
        List<SetupPageModel> pages = nullablePages
            .Where(static page => page is not null)
            .Select(static page => page!)
            .OrderBy(static page => page.Order)
            .ThenBy(static page => page.PageExpression, StringComparer.Ordinal)
            .ToList();

        foreach (SetupPageModel page in pages)
        {
            if (page.Method.ContainingType.ToDisplayString() != RegistryMetadataName)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidTargetDescriptor,
                    page.Method.Locations.FirstOrDefault(),
                    page.Method.Name));
                return;
            }
        }

        StringBuilder sb = new(4096);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// 此文件由 Source Generator 自动生成，请勿手动修改");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace PCL.Desktop.Features.Settings.Views;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class SetupPageRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.SetupPageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial bool IsDefined(global::PCL.Desktop.Features.Settings.Views.SetupPageSubType page) =>");
        if (pages.Count == 0)
        {
            sb.AppendLine("        false;");
        }
        else
        {
            sb.Append("        page is ");
            sb.Append(string.Join(" or ", pages.Select(static page => page.PageExpression)));
            sb.AppendLine(";");
        }
        sb.AppendLine();

        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.SetupPageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial global::PCL.Desktop.Controls.Legacy.MyPageRight CreatePage(global::PCL.Desktop.Features.Settings.Views.SetupPageSubType page) =>");
        sb.AppendLine("        page switch");
        sb.AppendLine("        {");
        foreach (SetupPageModel page in pages)
            sb.Append("            ").Append(page.PageExpression).Append(" => ").Append(page.Method.Name).AppendLine("(),");
        sb.AppendLine("            _ => throw new global::System.ArgumentOutOfRangeException(nameof(page), page, \"未知的设置页面。\")");
        sb.AppendLine("        };");
        sb.AppendLine();

        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"PCL.Desktop.SourceGenerators.SetupPageRegistryGenerator\", \"1.0.0.0\")]");
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
        sb.AppendLine("    public static partial string GetTitle(global::PCL.Desktop.Features.Settings.Views.SetupPageSubType page) =>");
        sb.AppendLine("        page switch");
        sb.AppendLine("        {");
        foreach (SetupPageModel page in pages)
            sb.Append("            ").Append(page.PageExpression).Append(" => ").Append(ToLiteral(page.Title)).AppendLine(",");
        sb.AppendLine("            _ => \"设置\"");
        sb.AppendLine("        };");
        sb.AppendLine("}");

        context.AddSource(
            "SetupPageRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string ToLiteral(string value) =>
        SymbolDisplay.FormatLiteral(value, quote: true);

    private static string GetEnumExpression(TypedConstant value)
    {
        if (value.Type is not INamedTypeSymbol enumType || value.Value is null)
            return string.Empty;

        foreach (ISymbol member in enumType.GetMembers())
        {
            if (member is IFieldSymbol { HasConstantValue: true } field &&
                Equals(field.ConstantValue, value.Value))
            {
                return enumType.ToDisplayString() + "." + field.Name;
            }
        }

        return enumType.ToDisplayString() + "." + value.Value;
    }

    private sealed class SetupPageModel
    {
        public SetupPageModel(
            IMethodSymbol method,
            string pageExpression,
            string title,
            int order)
        {
            Method = method;
            PageExpression = pageExpression;
            Title = title;
            Order = order;
        }

        public IMethodSymbol Method { get; }

        public string PageExpression { get; }

        public string Title { get; }

        public int Order { get; }
    }
}
