<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <Configurations>Beta;Debug;Release;DebugCI</Configurations>
    <AssemblyTitle>PCL.Test</AssemblyTitle>
    <Product>PCL.Test</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|ARM64'">
    <OutputPath>bin\ARM64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|ARM64'">
    <OutputPath>bin\ARM64\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Beta|AnyCPU'">
    <OutputPath>bin\Beta\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Beta|ARM64'">
    <OutputPath>bin\ARM64\Beta\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Beta|x64'">
    <OutputPath>bin\x64\Beta\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="fNbt" Version="1.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.TestPlatform.AdapterUtilities" Version="17.14.1" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PCL.Core\PCL.Core.csproj" />
  </ItemGroup>
</Project>