name: Issue Labeled
run-name: '#${{ github.event.issue.number }} ${{ github.event.issue.title }}'

on:
  issues:
    types: [labeled]

jobs:
  resolve-conflict:
    if: github.actor != 'PCL-Community-Bot'
    runs-on: ubuntu-latest
    steps:
      - name: Reset labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'set-labels'
          token: '${{ secrets.BOT }}'
          labels: '${{ github.event.label.name }}'

      - name: Mark breaking changes
        if: contains(github.event.issue.labels.*.name, '❗ 破坏性')
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: '${{ secrets.BOT }}'
          labels: '❗ 破坏性'

  close-as-completed:
    if: github.actor != 'PCL-Community-Bot' && github.event.label.name == '👌 完成'
    runs-on: ubuntu-latest
    steps:
      - name: Close as completed
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: '${{ secrets.BOT }}'
          close-reason: 'completed'

  close-as-not-planned:
    if: github.actor != 'PCL-Community-Bot' && (contains(github.event.label.name, '❌') || github.event.label.name == '😂 移交上游')
    runs-on: ubuntu-latest
    steps:
      - name: Close as not planned
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: '${{ secrets.BOT }}'
          close-reason: 'not_planned'

  report-to-upstream:
    if: github.event.label.name == '😂 移交上游'
    runs-on: ubuntu-latest
    steps:
      - name: Report to upstream
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: '${{ secrets.BOT }}'
          body: |
            @${{ github.event.issue.user.login }} 该提议不应由 CE 解决，请前往上游仓库提交。（如果上游仓库已经存在此反馈，可以去补充信息。）
            感谢您的反馈。